
If throwing exceptions:

  There is no security.output_filter defined in your application config file

it means an exception is being thrown before the exception can be handled.

Check the error log.

* Potential error in Sentry declaration


## Python/Robot Framework

Virtual environments: https://realpython.com/python-virtual-environments-a-primer/

## Testing

Unit Tests:
    cd admin
    vendor/bin/pest

Functional Testing:
    cd test/
